<?php /** @var $block \Mc\Blog\Block\PostList */ ?>
<h1><?php echo __('Latest Blog Posts') ?></h1>
<ul id="blog-post-list">
    <?php /** @var $post \Mc\Blog\Model\Post */ ?>
    <?php foreach ($block->getPosts() as $post): ?>
        <li class="blog-post-list-item">
            <h3 class="blog-post-item-title">
                <a href="<?php echo $post->getUrlKey() ?>"><?php echo $post->getTitle() ?></a>
            </h3>

            <div class="blog-post-item-meta">
                <strong><?php echo __('Created at:') ?></strong> <?php echo $post->getCreationTime() ?> - <strong><?php echo __('Posted By:'); ?></strong> <?php echo $post->getUsername(); ?>
            </div>

            <div class="blog-post-item-content">
                <?php echo $post->getContent(); ?>
            </div>
        </li>
    <?php endforeach; ?>
</ul>